### PR TITLE
Fix FC069, FC071, FC078

### PR DESCRIPTION
**Pull request by shortdudey123**
FC070 will still fail due to https://github.com/acrmp/foodcritic/issues/603

All the 3 fixed rules relate to the cookbook license

### CODE REVIEW

**Comment by guilhem** [comment]
@shortdudey123 FC070 is failing :(

**Comment by shortdudey123** [comment]
@guilhem yes, see my note and the linked issue :)

**Comment by guilhem** [comment]
oh my bad... ^^

**Comment by shortdudey123** [comment]
No problem!  `FC070` should pass in the next chefdk release with the updated foodcritic

**Pull request merged**
